### ISSUE TITLE
How to set up linter on windows 10?

### ISSUE THREAD

**Issue by lightbrush** [Jacajack/vscode-glsl-linter#1]
Hi Jacek,

Thanks for your great work. This extension works well on OSX, yet I do not understand how to set it up on Windows 10 system.
 
I downloaded the [glslang](https://github.com/KhronosGroup/glslang) and tried to set the validator path but failed.

![q7k 83 v58dkw 2 2 kbam](https://user-images.githubusercontent.com/10444778/52522628-c57b9900-2cc2-11e9-9820-9f66daab92c2.png)

I guessed that I must did something wrong...

**Comment by Jacajack** [comment]
I suspect that this may be just a bad path issue. On Windows paths use backslashes as directory separators. I don't know what the file is called, but please also make sure you didn't forget the `exe` extension. With these changes your path should look more like that:
`C:\GLSL\build\install\bin\glslangValidator.exe`

I should probably add some information for the user if the path is invalid in future versions.

**Comment by lightbrush** [comment]
Thanks Jacek, this problem was successfully solved~
