### ISSUE TITLE
Validator Args

### ISSUE THREAD

**Issue by jeffw387** [Jacajack/vscode-glsl-linter#3]
I'm trying to set up for linting targeting vulkan/spir-v, so I was attempting to pass `"-V"` to the compiler. When I pass any arguments (that I've tried so far) the linter seems to silently fail.

Here's the relevant section of `settings.json`
```
"glsl-linter.validatorPath": "/usr/bin/glslangValidator",
"glsl-linter.validatorArgs": "-V",
"glsl-linter.fileExtensions": {},
```

**Comment by Jacajack** [comment]
Indeed, it seems that any non-empty string causes it to fail. I'll look into it today.
Thanks for reporting! :+1:

**Comment by Jacajack** [comment]
Now, for more clarity `validatorArgs` is an array. I also improved error handling a bit, so you should be  notified if `glslangValidator` fails. I hope this helps!

**Comment by jeffw387** [comment]
Thanks for the quick response! I'll try it out soon.
